"""create transaction groups table

Revision ID: dd771ca2f83f
Revises: bcb6661b5271
Create Date: 2026-08-20 20:36:39.458264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd771ca2f83f'
down_revision: Union[str, Sequence[str], None] = 'bcb6661b5271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financial_event_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'POSTED', 'REVERSED', name='transaction_group_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['financial_event_id'], ['financial_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_groups')
    # ### end Alembic commands ###
